import {data,options,scenarios,descriptionExcerpt} from '../catalog.mjs';
import {selectProfiles} from '../engine.mjs';
import {groups,services,findServices,serviceStats} from './services.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('ru-RU').format(n);
const date=d=>new Date(d+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'});
const check='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>';
let group=0,screen='services',lastQuery=null,ticket=0;
for(const [id,key] of [['format','formats'],['language','languages']]) $('#'+id).replaceChildren(...(id==='language'?[new Option('Не имеет значения','')]:[]),...options[key].map(v=>new Option(v,v)));
function query(){return Object.fromEntries([...new FormData($('#search'))].map(([k,v])=>[k,['hours','budget'].includes(k)?Number(v):v]));}
function applyScenario(name){for(const [k,v] of Object.entries(scenarios[name]||scenarios.popular))$('#'+k).value=v;group=services.find(s=>s.name===$('#category').value).group;$('#service-search').value='';renderServices();updateChosen();}
function updateChosen(){const s=services.find(s=>s.name===$('#category').value);$('#selected-name').textContent=s.name;$('#chosen-name').textContent=s.name;$('#chosen-description').textContent=s.description;const illustration=$('#chosen-illustration');if(illustration){const asset=s.group===1?'photo':['Декоратор','Флорист'].includes(s.name)?'decor':['Ведущий','Ведущий церемонии','Лайв-бэнд'].includes(s.name)?'host':null;illustration.hidden=!asset;if(asset){const path='../assets/generated/service-'+asset+'.png';if(illustration.getAttribute('src')!==path)illustration.src=path;illustration.dataset.kind=asset;}else{illustration.removeAttribute('src');delete illustration.dataset.kind;}}$('#context-summary').textContent=`${$('#city').value} · ${$('#format').value}`;$('#dirty').hidden=!lastQuery||JSON.stringify(lastQuery)===JSON.stringify(query());}
function renderServices(){const term=$('#service-search').value;$('#groups').innerHTML=groups.map((g,i)=>`<button type="button" data-group="${i}" aria-pressed="${!term.trim()&&group===i}">${g}<small>${services.filter(s=>s.group===i).length}</small></button>`).join('');const shown=term.trim()?findServices(term):services.filter(s=>s.group===group);$('#group-title').textContent=term.trim()?'Результаты поиска':groups[group];$('#service-count').textContent=`Услуг: ${shown.length}`;
 $('#service-list').innerHTML=shown.length?shown.map(s=>{const stats=serviceStats(data,$('#city').value,s.name),selected=s.name===$('#category').value;return `<button type="button" class="service" data-service="${esc(s.name)}" aria-pressed="${selected}"><span class="service-name">${s.name}<span class="choice-mark" aria-hidden="true">${selected?check:''}</span></span><span class="service-description">${s.description}</span><span class="service-data">${stats.count?'Профилей: '+stats.count:'Пока нет в городе'}${stats.count?'<span class="dot"> · </span><strong>от '+money(stats.min)+' ₸</strong>':''}</span></button>`;}).join(''):'<div class="no-services"><h3>Такой услуги не нашли</h3><p>Попробуйте другое название или вернитесь к группам.</p><button type="button" class="text-button" data-clear>Сбросить поиск</button></div>';
}
function go(next,focus=true){if(next==='results'&&!lastQuery)return;screen=next;for(const id of ['services','conditions','results'])$('#'+id+'-screen').hidden=id!==next;$$('[data-step]').forEach(b=>{if(b.closest('.journey')){b.removeAttribute('aria-current');if(b.dataset.step===next)b.setAttribute('aria-current','step');if(b.dataset.step==='results')b.disabled=!lastQuery;}});updateChosen();if(focus){const heading=$('#'+({services:'service-title',conditions:'conditions-title',results:'results-title'}[next]));heading.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}}
function validate(){const q=query();let first=null;for(const id of ['date','budget','hours']){let text='';if(id==='date'&&(!q.date||q.date<'2026-09-23'||q.date>'2026-12-31'))text='Выберите дату с 23 сентября по 31 декабря 2026.';if(id==='budget'&&(!Number.isFinite(q.budget)||q.budget<=0))text='Укажите бюджет больше нуля.';if(id==='hours'&&(!Number.isFinite(q.hours)||($('#hours').value!==''&&q.hours<1)||q.hours>24||!Number.isInteger(q.hours)))text='Укажите от 1 до 24 целых часов или оставьте поле пустым.';$('#'+id+'-error').textContent=text;$('#'+id).setAttribute('aria-invalid',String(!!text));if(text&&!first)first=id;}if(first){go('conditions',false);if(first==='hours')$('#extra').open=true;$('#'+first).focus();return false;}return true;}
const reasonLabels={busy:'заняты на выбранную дату',budget:'начальная цена выше бюджета',format:'не работают с этим форматом',language:'не работают на выбранном языке',hours:'не подходят по длительности'};
const fields={busy:['date','Изменить дату'],budget:['budget','Изменить бюджет'],format:['format','Изменить формат'],language:['language','Изменить язык'],hours:['hours','Изменить длительность']};
function edit(field){go(['city','format','category'].includes(field)?'services':'conditions',false);if(field==='category'){$('#service-search').focus();$('#service-search').scrollIntoView({block:'center'});}else{if(['hours','language'].includes(field))$('#extra').open=true;$('#'+field).focus();$('#'+field).scrollIntoView({block:'center'});}}
function card(p,q){const provenance=[p.synthetic?'Синтетический профиль':'Анонимизированный профиль',p.priceImputed?'Цена проставлена в датасете':'',p.cityImputed?'Город проставлен в датасете':''].filter(Boolean).join('. ');
 const terms=[`Работает с форматом «${q.format.toLowerCase()}»`,p.price===q.budget?'начальная цена равна бюджету':`начальная цена ниже бюджета на ${money(q.budget-p.price)} ₸`];
 if(q.language)terms.push(`язык — ${q.language.toLowerCase()}`);
 if(q.hours)terms.push(p.hours===null?'услуга без привязки к часам':`${q.hours} ч укладываются в лимит ${p.hours} ч`);
 return `<article class="vendor" data-profile-id="${esc(p.id)}"><div><h2>${esc(p.name)}</h2><p class="vendor-meta">${esc(q.category)} · ${esc(p.city)}</p></div><div class="price"><small>от</small> ${money(p.price)} ₸${p.priceImputed?' *':''}<p>за мероприятие${p.priceImputed?' · цена проставлена':''}</p></div><div class="available">${check}<span>Свободен · ${date(q.date)}<small>По данным каталога</small></span></div><div class="why"><h3>Почему подходит</h3><p>${esc(terms.join('; '))}.</p><p class="source">Из описания: «${esc(descriptionExcerpt(p))}»</p></div><dl class="facts"><div><dt>Языки</dt><dd>${esc(p.languages.join(', '))}</dd></div><div><dt>Длительность</dt><dd>${p.hours===null?'Без привязки к часам':'До '+p.hours+' часов'}</dd></div></dl><details><summary>Подробнее о подрядчике</summary><p>${esc(p.detail)}</p><p>Категории: ${esc(p.categories.join(', '))}.<br>Форматы: ${esc(p.formats.join(', '))}.</p><p class="provenance">${esc(provenance)}. Имя вымышленное.</p></details></article>`;
}
function empty(title,body,buttons,extra=''){return `<div class="empty"><h2>${title}</h2><p>${body}</p>${extra}<div class="empty-actions">${buttons}</div></div>`;}
const editButton=(field,label)=>`<button class="text-button" data-edit="${field}">${label} <span aria-hidden="true">↗</span></button>`;
async function run(fail=false){if(!validate())return;const id=++ticket,q=query(),previous=lastQuery;lastQuery=q;go('results');$('#submit').disabled=true;$('#result-content').setAttribute('aria-busy','true');$('#results-title').textContent='Подбираем варианты…';$('#results-subtitle').textContent='Проверяем условия и доступность в демонстрационном каталоге.';$('#query-summary').innerHTML=[q.category,q.city,q.format,date(q.date),`до ${money(q.budget)} ₸`,q.language,q.hours?q.hours+' ч':''].filter(Boolean).map(s=>`<span>${esc(s)}</span>`).join('');$('#price-note').hidden=true;$('#result-content').innerHTML='<div class="loading"><span class="spinner" aria-hidden="true"></span>Подбираем подрядчиков по вашим условиям</div>';
 await new Promise(r=>setTimeout(r,650));if(id!==ticket)return;$('#submit').disabled=false;$('#result-content').removeAttribute('aria-busy');
 if(fail){$('#results-title').textContent='Не получилось завершить подбор.';$('#results-subtitle').textContent='Параметры сохранены.';$('#result-content').innerHTML=empty('Попробуем ещё раз?','Это демонстрация технического сбоя. Повторный запрос использует ваши условия.','<button class="primary" data-action="retry">Повторить подбор</button>');return;}
 const r=selectProfiles(data,q);$('#results-title').textContent=r.state==='success'?'Ваш короткий список.':r.state==='absent'?'Пока нет такой услуги.':'Условия не совпали.';$('#results-subtitle').textContent=r.state==='success'?`Подходящих профилей: ${r.total}. ${r.total>3?'Показываем первые три. ':''}По возрастанию начальной цены.`:'Предложим, что можно изменить. Решение — за вами.';
 if(r.state==='success'){const why=Object.entries(r.reasons).filter(([,n])=>n).map(([k,n])=>`${n} — ${reasonLabels[k]}`).join('; ');$('#result-content').innerHTML=(r.total<3?`<div class="notice">Подходящих вариантов: ${r.total}. ${r.pool===r.total?'В этой категории и городе всего '+r.pool+' в каталоге.':'Остальные не прошли условия: '+why+'. У одного профиля может быть несколько причин.'}</div>`:'')+'<div class="comparison">'+r.items.map(p=>card(p,q)).join('')+'</div>';$('#price-note').hidden=false;}
 else if(r.state==='absent')$('#result-content').innerHTML=empty('В городе нет этой категории',`В каталоге нет категории «${esc(q.category)}» для города ${esc(q.city)}. Дата и бюджет не повлияли на результат.`,editButton('category','Выбрать другую услугу')+editButton('city','Изменить город'));
 else{const reasons=Object.entries(r.reasons).filter(([,n])=>n);$('#result-content').innerHTML=empty('Подрядчики есть, совпадений нет',`В городе ${esc(q.city)} профилей в категории «${esc(q.category)}»: ${r.pool}. Ни один не проходит все условия.`,reasons.map(([k])=>editButton(...fields[k])).join(''),'<ul>'+reasons.map(([k,n])=>`<li>${n} — ${reasonLabels[k]}</li>`).join('')+'</ul><p>У одного профиля может быть несколько причин.</p>');}
 if(previous&&previous.date!==q.date&&Object.keys(q).every(k=>k==='date'||q[k]===previous[k])){const removed=selectProfiles(data,previous).items.filter(p=>p.busy.includes(q.date));if(removed.length)$('#result-content').insertAdjacentHTML('afterbegin',`<div class="notice">На ${date(q.date)} заняты: ${removed.map(p=>esc(p.name)).join(', ')}. Эти профили исключены из нового подбора.</div>`);}
 updateChosen();
}
$('#continue').addEventListener('click',()=>go('conditions'));
$('#service-search').addEventListener('input',renderServices);
$('#service-search').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const matches=findServices(e.target.value);if(matches.length===1){$('#category').value=matches[0].name;renderServices();updateChosen();}}});
$('#search').addEventListener('submit',e=>{e.preventDefault();if(screen==='services')go('conditions');else run();});
$('#search').addEventListener('input',updateChosen);
$('#city').addEventListener('change',()=>{renderServices();updateChosen();});
document.addEventListener('click',e=>{
 const step=e.target.closest('[data-step]');if(step&&!step.disabled){e.preventDefault();go(step.dataset.step);}
 const groupButton=e.target.closest('[data-group]');if(groupButton){if(groupButton.closest('footer'))go('services');group=Number(groupButton.dataset.group);$('#service-search').value='';renderServices();$('#groups [data-group="'+group+'"]').focus();}
 const service=e.target.closest('[data-service]');if(service){$('#category').value=service.dataset.service;renderServices();updateChosen();$$('[data-service]').find(b=>b.dataset.service===$('#category').value)?.focus();}
 if(e.target.closest('[data-clear]')){$('#service-search').value='';renderServices();$('#service-search').focus();}
 const editTarget=e.target.closest('[data-edit]');if(editTarget)edit(editTarget.dataset.edit);
 if(e.target.closest('[data-action="retry"]'))run();
 const scenario=e.target.closest('[data-scenario]');if(scenario){ticket++;$('#submit').disabled=false;$('#result-content').removeAttribute('aria-busy');applyScenario(scenario.dataset.scenario);for(const id of ['date','budget','hours']){$('#'+id+'-error').textContent='';$('#'+id).removeAttribute('aria-invalid');}if(scenario.dataset.scenario==='initial'){lastQuery=null;go('services');}else run(scenario.dataset.scenario==='error');}
});
applyScenario('popular');go('services',false);
if(new URLSearchParams(location.search).get('example')==='1')run();
